### PR TITLE
Stable hashing for node selection in the payer

### PR DESCRIPTION
**Pull request by mkysel**
Stable hashing in the payer to pick the correct node to send the write to. Hash is calculated based on the largest known ID and the topic.

This also pulls the changes to protos to stop using the originator_id and use is_commit instead.

Right now the client does not implement is_commit correctly. And hard codes the nodeID to 100 in all cases.

In the case of off-chain messages, this still guarantees that the message was written on that particular node.
In case of on-chain commits, the guarantee introduced in #418 somewhat holds. Since the client is no longer selecting a node, the payer will automatically detect which node should be seen as the preferred node and will block until that node has read the chain.

In neither case can we guarantee that any other node has read any write.

The stable hashing algorithm is pretty naive and might eventually need some enhancements. There are two issues that I see with it as is (which is the standard implementation):
- if there are node ID gaps, the next nodeID gets double or more of the traffic
- if we issue a new node ID it might rehash

The payer does not yet have any retry logic, it does not check the liveness of the nodes, etc. All of that has to happen in a future PR.

Relates to:
- https://github.com/xmtp/XIPs/pull/85
- https://github.com/xmtp/proto/pull/242

Fixes https://github.com/xmtp/libxmtp/issues/1455

## Summary by CodeRabbit

- **New Features**
  - Introduced an enhanced routing mechanism that leverages stable hashing for more optimal node selection and balanced message distribution.

- **Refactor**
  - Standardized how routing data is assigned, ensuring consistent handling of message originators.
  - Refined criteria for routing validation and blockchain publishing, improving overall reliability.

- **Tests**
  - Expanded test coverage to verify stable node selection, robust message routing, and balanced topic assignments.
  - Enhanced test setup to utilize a mock registry for improved clarity and control over interactions.

### CODE REVIEW

File: pkg/api/payer/nodeSelector.go [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+	if len(nodes) == 0 {
+		return 0, errors.New("no available nodes")
+	}
+
+	// Sort nodes to ensure stability
+	sort.Slice(nodes, func(i, j int) bool { return nodes[i].NodeID < nodes[j].NodeID })
+
+	topicHash := HashKey(topic)
+
+	// we do not want to hash the entire available hash space, just consider up to the largest NodeID issued
```
Comment (neekolas) [inline pkg/api/payer/nodeSelector.go:48]: I want to make sure my intuitions are correct here.

Let's say we have nodes 100, 200, and 300.

If we add node 400, what % of the topics will shift to point to a different node? I think by including the highest node ID in the `topicHash` we might defeat the purpose of consistent hashing, which is consistency of selection.

Am I misunderstanding this?

Comment (neekolas) [reply pkg/api/payer/nodeSelector.go:48]: Typically when I think of consistent hashing I think of having the hash be `% 360` (or some other constant) and distributing the node IDs equally between 0 and that constant.

Comment (mkysel) [reply pkg/api/payer/nodeSelector.go:48]: yes. I point out these limitations in the PR description. I am happy to brainstorm on how to get this right.

Comment (neekolas) [reply pkg/api/payer/nodeSelector.go:48]: Just spitballing

We define some constant for the size of the space. Let's say 360.

Then we split the nodes evenly over that space.

```python
spacing = 360 / num_nodes
node_locations = [spacing * index for index, node in enumerate(nodes)] // assumes nodes are sorted by ID
```

Then we can just `hash(topic) % 360` for each topic and put it somewhere in the space. As we add nodes the locations would move but only slightly.

Comment (mkysel) [reply pkg/api/payer/nodeSelector.go]: the new commit does that. Just in a 32bit space.

File: pkg/api/payer/nodeSelector_test.go [hunk 2]
```diff
@@ -0,0 +1,228 @@
...
+		}
+	}
+	t.Logf("Target Buckets: %v", targetBuckets)
+
+	// Compute expected balance
+	expectedPerNode := totalRequests / uint32(len(nodes))
+	tolerance := float64(expectedPerNode) * 0.05 // 10% tolerance
+	t.Logf("Target Tolerance: %v", tolerance)
+
+	// Verify that each bucket is within ±10% of expected distribution
```
Comment (neekolas) [inline pkg/api/payer/nodeSelector_test.go:222]: Great test

**Review by neekolas — APPROVED** [review]
